eclipse-daanse/org.eclipse.daanse.board.app

- .github/workflows/docker_build.yml
- .github/workflows/ts_yarn_build.yml
> [ci] update action/cache to v4.2.3 in hash

- .github/workflows/docker_build.yml
- .github/workflows/push_next.yml
- .github/workflows/ts_yarn_build.yml
> [ci] update checkout plugin version

- .github/workflows/docker_build.yml
- Docker/Dockerfile
> fix Docker build

- package.json
- packages/app/default/package.json
- packages/lib/core/package.json
- packages/lib/module1/package.json
- packages/ui/vue/widget/sample/package.json
https://github.com/eclipse-daanse/org.eclipse.daanse.board.app/issues/34
> add publichConfig

- packages/app/default/package.json
- packages/lib/core/package.json
- packages/lib/module1/package.json
- packages/ui/vue/widget/sample/package.json
https://github.com/eclipse-daanse/org.eclipse.daanse.board.app/issues/34
> #34 fix repos field in package.json

- .github/workflows/build_and_disribute_electron.yml
> CHANGE working-directory in CI electron

- .github/workflows/build_and_disribute_electron.yml
- packages/app/default/package.json
- packages/app/electron/package.json
- packages/lib/core/package.json
- packages/lib/module1/package.json
- packages/ui/vue/widget/sample/package.json
> build step electron

- README.md
- package.json
- tools/createPackage.js
- tools/package.json.js
- tools/tmpl/src/index.ts
- tools/tmpl/tsconfig.json
- tools/vite.config.js
> build script for creating packages and readme update

- packages/lib/connection/mqtt/__tests__/test.test.ts
- packages/lib/connection/mqtt/package.json
- packages/lib/connection/mqtt/src/classes/index.ts
- packages/lib/connection/mqtt/src/index.ts
- packages/lib/connection/mqtt/tsconfig.json
- packages/lib/connection/mqtt/vite.config.ts
> Create mqtt connection

- packages/lib/connection/ws/__tests__/test.test.ts
- packages/lib/connection/ws/package.json
- packages/lib/connection/ws/src/classes/index.ts
- packages/lib/connection/ws/src/index.ts
- packages/lib/connection/ws/tsconfig.json
- packages/lib/connection/ws/vite.config.ts
> Create websocket connection

- packages/lib/datasource/rss/__tests__/test.test.js
- packages/lib/datasource/rss/package.json
- packages/lib/datasource/rss/src/classes/index.ts
- packages/lib/datasource/rss/src/index.ts
- packages/lib/datasource/rss/tsconfig.json
- packages/lib/datasource/rss/vite.config.ts
Closes #78 
Should be merged after #83 and being rebased
> Add RSS store

- packages/lib/datasource/graphql/__tests__/test.test.js
- packages/lib/datasource/graphql/package.json
- packages/lib/datasource/graphql/src/classes/index.ts
- packages/lib/datasource/graphql/src/index.ts
- packages/lib/datasource/graphql/tsconfig.json
- packages/lib/datasource/graphql/vite.config.ts
Closes #77 
Should be merged after #83 and being rebased
> Add graphql store

- packages/lib/datasource/ws/__tests__/test.test.js
- packages/lib/datasource/ws/package.json
- packages/lib/datasource/ws/src/classes/index.ts
- packages/lib/datasource/ws/src/index.ts
- packages/lib/datasource/ws/tsconfig.json
- packages/lib/datasource/ws/vite.config.ts
Closes #79
Should be merged after #83 and being rebased
> Add ws/mqtt store

- packages/lib/repository/connection/__tests__/test.test.ts
- packages/lib/repository/connection/package.json
- packages/lib/repository/connection/src/classes/index.ts
- packages/lib/repository/connection/src/index.ts
- packages/lib/repository/connection/tsconfig.json
- packages/lib/repository/connection/vite.config.ts
- yarn.lock
> Add connection repo with proper tests

- packages/lib/factory/datasource/__tests__/test.test.ts
- packages/lib/factory/datasource/package.json
- packages/lib/factory/datasource/src/classes/index.ts
- packages/lib/factory/datasource/src/index.ts
- packages/lib/factory/datasource/tsconfig.json
- packages/lib/factory/datasource/vite.config.ts
> Add datasource factory

- packages/lib/datasource/csv/src/classes/index.ts
- packages/lib/datasource/rest/package.json
- packages/lib/datasource/rest/src/classes/index.ts
- packages/lib/utils/helpers/__tests__/test.test.ts
- packages/lib/utils/helpers/package.json
- packages/lib/utils/helpers/src/classes/csv.ts
- packages/lib/utils/helpers/src/classes/helpers.ts
- packages/lib/utils/helpers/src/index.ts
- packages/lib/utils/helpers/tsconfig.json
- packages/lib/utils/helpers/vite.config.ts
> Added helpers. CSV, basic parsing helpers, fixed stores

- packages/lib/repository/widget/package.json
- packages/lib/repository/widget/src/classes/index.ts
- packages/lib/repository/widget/src/index.ts
- packages/lib/repository/widget/tsconfig.json
- packages/lib/repository/widget/vite.config.ts
> Add widget repository

- packages/ui/vue/widget/wrapper/package.json
- packages/ui/vue/widget/wrapper/src/WidgetWrapper.vue
- packages/ui/vue/widget/wrapper/src/index.ts
- packages/ui/vue/widget/wrapper/tsconfig.json
- packages/ui/vue/widget/wrapper/vite.config.ts
> Add widget wrapper

- .github/workflows/docker_build.yml
adds riscv64 to docker build ci
#99
> add riscv64 to docker build ci

- .github/workflows/pr_run_daanse.yml
https://github.com/eclipse-daanse/org.eclipse.daanse.board.app/issues/169
> daanse action

- .github/dependabot.yml
> set open-pull-requests-limit: 25

- packages/app/default/e2e/vue.spec.ts
- tools/test/screenshoter/screenshoter.ts
> add Bbox and description to CuePoints

- packages/app/default/src/main.ts
- packages/ui/vue/widget/chart/src/index.ts
- packages/ui/vue/widget/icon/src/index.ts
- packages/ui/vue/widget/image/src/index.ts
- packages/ui/vue/widget/progress/src/index.ts
- packages/ui/vue/widget/sample/src/index.ts
- packages/ui/vue/widget/svg/base/src/index.ts
- packages/ui/vue/widget/svg/repeat/src/index.ts
- packages/ui/vue/widget/table/data/src/index.ts
- packages/ui/vue/widget/table/pivot/src/index.ts
- packages/ui/vue/widget/text/plain/src/index.ts
- packages/ui/vue/widget/text/rich/src/index.ts
- packages/ui/vue/widget/video/src/index.ts
> Fix widget init function

- packages/app/default/package.json
- packages/app/default/src/App.vue
- packages/app/default/src/components/common/AddWidgetWindow.vue
- packages/app/default/src/main.ts
- packages/lib/datasource/base/package.json
- packages/lib/datasource/base/tsconfig.json
- packages/lib/datasource/ogcsta/src/classes/OgcSta.ts
- packages/ui/vue/composables/package.json
- packages/ui/vue/composables/src/useDatasourceRepository.ts
- packages/ui/vue/composables/vite.config.ts
- packages/ui/vue/widget/icon/package.json
- packages/ui/vue/widget/icon/src/IconWidget.vue
- packages/ui/vue/widget/icon/src/index.ts
- packages/ui/vue/widget/icon/tsconfig.json
- packages/ui/vue/widget/icon/vite.config.ts
- packages/ui/vue/widget/map/package.json
- packages/ui/vue/widget/map/src/MapsWidget.vue
- packages/ui/vue/widget/map/src/MapsWidgetSettings.vue
- packages/ui/vue/widget/map/src/index.ts
- packages/ui/vue/widget/map/src/parts/MapPreviewPoint.vue
- packages/ui/vue/widget/map/src/parts/RendererModal.vue
- packages/ui/vue/widget/map/src/parts/styler/OberservationsStyler.vue
- packages/ui/vue/widget/map/src/parts/styler/PlacementSytler.vue
- packages/ui/vue/widget/map/src/parts/styler/PointStyler.vue
- packages/ui/vue/widget/map/vite.config.ts
- yarn.lock
> add Maps Widget

- packages/app/default/package.json
- packages/app/default/src/components/datasources/DatasourceEditor.vue
- packages/app/default/src/main.ts
- packages/lib/connection/rest/src/classes/index.ts
- packages/lib/datasource/sparql/package.json
- packages/lib/datasource/sparql/src/classes/SparqlStore.ts
- packages/lib/datasource/sparql/src/index.ts
- packages/lib/datasource/sparql/src/interfaces/Constances.ts
- packages/lib/datasource/sparql/src/interfaces/ISparqlStoreConfiguration.ts
- packages/lib/datasource/sparql/tsconfig.json
- packages/lib/datasource/sparql/vite.config.ts
- packages/lib/repository/connection/src/classes/index.ts
- packages/ui/vue/datasource/sparql/package.json
- packages/ui/vue/datasource/sparql/src/Preview.vue
- packages/ui/vue/datasource/sparql/src/Settings.vue
- packages/ui/vue/datasource/sparql/src/index.ts
- packages/ui/vue/datasource/sparql/tsconfig.json
- packages/ui/vue/datasource/sparql/vite.config.ts
- yarn.lock
> add sparql datasource

- packages/app/default/package.json
- packages/app/default/src/components/datasources/DatasourceList.vue
- packages/app/default/src/main.ts
- packages/lib/datasource/rest/__tests__/test.test.ts
- packages/lib/datasource/rest/src/classes/index.ts
- packages/lib/repository/connection/src/classes/index.ts
- packages/lib/repository/datasource/src/classes/index.ts
- packages/ui/vue/plugins/endpointfinder/package.json
- packages/ui/vue/plugins/endpointfinder/src/components/Searchcard/SearchResultCard.vue
- packages/ui/vue/plugins/endpointfinder/src/components/utils/Ellipsis/Ellipsis.vue
- packages/ui/vue/plugins/endpointfinder/src/composeables/FormatComposeable.ts
- packages/ui/vue/plugins/endpointfinder/src/index.ts
- packages/ui/vue/plugins/endpointfinder/src/modals/EndPointfinderModal.vue
- packages/ui/vue/plugins/endpointfinder/src/modals/FilterModal.vue
- packages/ui/vue/plugins/endpointfinder/src/queryBuilder/FilterAPI.ts
- packages/ui/vue/plugins/endpointfinder/src/queryBuilder/QueryBuilder.ts
- packages/ui/vue/plugins/endpointfinder/src/queryBuilder/QueryBuilderAPI.ts
- packages/ui/vue/plugins/endpointfinder/src/sparql/SparqlEndpointRegistry.api.ts
- packages/ui/vue/plugins/endpointfinder/src/sparql/SparqlEndpointRegistry.ts
- packages/ui/vue/plugins/endpointfinder/tsconfig.json
- packages/ui/vue/plugins/endpointfinder/vite.config.ts
- packages/ui/vue/stores/connection/src/index.ts
- packages/ui/vue/stores/connection/src/store/ConnectionsPinia.ts
- packages/ui/vue/stores/datasouce/src/index.ts
- packages/ui/vue/stores/datasouce/src/store/DatasourcePinia.ts
- yarn.lock
> endpointfinder_ui

- packages/app/default/package.json
- packages/app/default/src/pages/EditReport.vue
- packages/ui/vue/plugins/endpointfinder/package.json
- packages/ui/vue/plugins/endpointfinder/src/modals/EndPointfinderModal.vue
- packages/ui/vue/stores/layout/package.json
- packages/ui/vue/stores/layout/src/index.ts
- packages/ui/vue/stores/layout/src/store/LayoutsPinia.ts
- packages/ui/vue/stores/layout/tsconfig.json
- packages/ui/vue/stores/layout/vite.config.ts
- packages/ui/vue/stores/widgets/package.json
- packages/ui/vue/stores/widgets/src/index.ts
- packages/ui/vue/stores/widgets/src/store/WidgetsPinia.ts
- packages/ui/vue/stores/widgets/tsconfig.json
- packages/ui/vue/stores/widgets/vite.config.ts
- packages/ui/vue/widget/table/data/src/index.ts
> add widget adding dialog step

- packages/lib/datasource/sparql/src/classes/SparqlStore.ts
- packages/lib/datasource/sparql/src/interfaces/ISparqlStoreConfiguration.ts
> add parse to DataTable

- packages/lib/utils/helpers/src/classes/helpers.ts
- packages/lib/utils/helpers/src/index.ts
- packages/ui/vue/widget/progress/package.json
- packages/ui/vue/widget/progress/src/ProgressWidget.vue
- packages/ui/vue/widget/progress/vite.config.ts
- packages/ui/vue/widget/text/plain/package.json
- packages/ui/vue/widget/text/plain/src/TextWidget.vue
- packages/ui/vue/widget/text/plain/vite.config.ts
- packages/ui/vue/widget/text/rich/package.json
- packages/ui/vue/widget/text/rich/src/RichTextWidget.vue
- packages/ui/vue/widget/text/rich/vite.config.ts
> Add parser for data from stores in text

- packages/ui/vue/widget/table/data/package.json
- packages/ui/vue/widget/table/data/src/DataTableWidget.vue
- packages/ui/vue/widget/table/data/src/DataTableWidgetSettings.vue
- packages/ui/vue/widget/table/data/vite.config.ts
> Add setting for datatable header color

- packages/lib/persistence/git/openapitools.json
- packages/lib/persistence/git/package.json
- packages/lib/persistence/git/src/git_api/conf/example.json
- packages/lib/persistence/git/src/git_api/generated/gitea/definition/swagger_short.json
- packages/lib/persistence/git/src/index.ts
- packages/lib/persistence/git/tsconfig.json
- packages/lib/persistence/git/vite.config.ts
> git lib for persistence

- .github/workflows/ts_yarn_build.yml
- package.json
- turbo.json
- yarn.lock
pervents double builds caches local builds
> add turbo build

- packages/app/default/src/components/saveLoad/Default.vue
- packages/app/default/src/pages/SaveLoad.vue
- packages/lib/settings/manager/src/classes/SettingsManager.ts
- packages/ui/vue/persistence/git/src/GitRepositoryV.vue
- yarn.lock
fix reload after save
fix get connection error on load
> fix not loading Repos if on sub route

- .github/workflows/ts_yarn_build.yml
- package.json
> add 16 concurrency and 65536 ram

- packages/app/default/package.json
- packages/app/default/src/components/saveLoad/Default.vue
- packages/app/default/src/pages/EditReport.vue
- packages/app/default/src/pages/SaveLoad.vue
- packages/lib/persistence/local/src/classes/LocalRepositoryImpl.ts
- packages/lib/persistence/util/package.json
- packages/ui/vue/persistence/git/src/GitRepositoryV.vue
- packages/ui/vue/widget/map/src/MapsWidget.vue
- packages/ui/vue/widget/map/src/MapsWidgetSettings.vue
- packages/ui/vue/widget/map/src/Settings.d.ts
- packages/ui/vue/widget/map/src/parts/RendererModal.vue
- packages/ui/vue/widget/map/src/parts/conditionLogic/ConditionSettings.vue
- packages/ui/vue/widget/map/src/parts/dataLabelRenderer/TLCDataLabelRenderer.vue
> fix load Maps

- packages/ui/vue/composables/src/useVariableRepository.ts
- packages/ui/vue/widget/mermaid/src/MermaidWidget.vue
- yarn.lock
> fix maramid

- packages/ui/vue/widget/vanta/package.json
> three 0.134.0

- packages/lib/connection/xmla/src/classes/index.ts
- packages/lib/connection/xmla/src/utils/SOAPInBrowser/src/client.ts
- packages/lib/connection/xmla/src/utils/SOAPInBrowser/src/soap.ts
- packages/lib/connection/xmla/src/utils/XMLAClient.ts
- packages/lib/datasource/xmla/src/classes/index.ts
- packages/ui/vue/connection/xmla/src/Settings.vue
> Added basic authentication for xmla connection and datasource

- packages/app/default/package.json
- packages/app/default/src/main.ts
- packages/lib/composer/ogc/package.json
- packages/lib/composer/ogc/src/classes/index.ts
- packages/lib/composer/ogc/src/index.ts
- packages/lib/composer/ogc/tsconfig.json
- packages/lib/composer/ogc/vite.config.ts
- packages/lib/datasource/csv/src/classes/index.ts
- packages/ui/vue/composer/ogc/package.json
- packages/ui/vue/composer/ogc/src/Preview.vue
- packages/ui/vue/composer/ogc/src/Settings.vue
- packages/ui/vue/composer/ogc/src/index.ts
- packages/ui/vue/composer/ogc/tsconfig.json
- packages/ui/vue/composer/ogc/vite.config.ts
> Created ogc features composer
